language: java
jdk: oraclejdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
script: mvn -e verify
notifications:
  email:
    recipients:
      - guestliveid@gmail.com
    on_failure: always
    on_success: change